# -*- coding: utf-8 -*-
"""Generate VoiceLineIds.cs + SpeakerNames.cs from the game data (single source of truth)."""
import io, sys, os, re, collections
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
import UnityPy

DATA = r"D:\Steam\steamapps\common\The NOexistenceN of you AND me\TheNOexistenceNofyouANDme_Data\data.unity3d"
TSV = r"D:\DSHWorkBase\noexistence_a11y\台词与角色对照.txt"
OUTDIR = r"D:\DSHWorkBase\noexistence_a11y\mod\src\NoExistenceA11y"

# ---- 1. speaker display names, from the zh-CN source CharacterNames document ----
env = UnityPy.load(DATA)
copies = []
for o in env.objects:
    if o.type.name != "TextAsset":
        continue
    try:
        d = o.read()
        s = getattr(d, "m_Script", b"")
        if getattr(d, "m_Name", "?") == "CharacterNames":
            copies.append(s if isinstance(s, str) else bytes(s).decode("utf-8", "replace"))
    except Exception:
        pass

names = {}
for body in copies:
    if body.lstrip().startswith(("\ufeff#,", "#,")) or body.count(";") > 20:
        continue
    for ln in body.splitlines():
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.*)$", ln)
        if m:
            names.setdefault(m.group(1), m.group(2).strip())
    if names:
        break

# 手动补齐的运行时标签（不在登记表里，但剧本会用到）
names["???"] = "未知"

print("说话人显示名 %d 条" % len(names))

# ---- 2. voiced line ids ----
rows = []
for line in open(TSV, encoding="utf-8"):
    p = line.rstrip("\n").split("\t")
    if len(p) == 6 and p[0].startswith("Prologue"):
        rows.append(p)

voiced = sorted({p[0] + "/" + p[1] for p in rows if p[4] == "配音"})
allids = sorted({p[0] + "/" + p[1] for p in rows})
print("对话行 %d | 有配音 %d | 需 TTS %d" % (len(allids), len(voiced), len(allids) - len(voiced)))

# ---- 2b. 只看行号的配音集合（游戏语音文件就是这么命名的：~<hash>）----
#
# 为什么必须有这一份：同一个行号会被**多个剧本复用**（实测 ~4ca079d5 出现在 3 个剧本、
# ~3ea899f 两个），而按「剧本/行号」登记时只会登记其中一个 —— 复用的那些剧本查不到 key，
# 补丁就把**有配音的行当成无配音**，TTS 叠在角色语音上。
# 实测核对：844 条有配音的行里有 8 条因此漏判。语音文件是按行号命名的，所以正确口径就是只看行号。
voiced_ids = set()
for o in env.objects:
    if o.type.name != "AudioClip":
        continue
    try:
        n = getattr(o.read(), "m_Name", "") or ""
    except Exception:
        continue
    if re.fullmatch(r"~[0-9a-f]{5,}", n):
        voiced_ids.add(n.lstrip("~"))
voiced_ids = sorted(voiced_ids)
print("按行号命名的语音片段 %d 条（只看行号的配音集合）" % len(voiced_ids))

# ---- 3. write ----
enc = "utf-8"
nl = "\r\n"

with open(os.path.join(OUTDIR, "VoiceLineIds.cs"), "w", encoding=enc, newline=nl) as f:
    f.write("// <auto-generated> by gen_voicelist.py — do not edit by hand.\n")
    f.write("// %d 条有配音的对话行（键 = 剧本/行号）。命中则只放游戏语音、抑制 TTS。\n" % len(voiced))
    f.write("using System.Collections.Generic;\n\nnamespace NoExistenceA11y\n{\n")
    f.write("    internal static class VoiceLineIds\n    {\n")
    f.write("        public static readonly HashSet<string> Voiced = new HashSet<string>\n        {\n")
    for v in voiced:
        f.write('            "%s",\n' % v)
    f.write("        };\n")
    f.write("\n")
    f.write("        /// <summary>只看行号（不带剧本名）。游戏语音文件就是这么命名的。</summary>\n")
    f.write("        public static readonly HashSet<string> VoicedIds = new HashSet<string>\n        {\n")
    for v in voiced_ids:
        f.write('            "%s",\n' % v)
    f.write("        };\n")
    f.write("\n")
    f.write("        /// <summary>\n")
    f.write("        /// 这一行到底有没有配音。key 形如 Prologue1_7/~4ca079d5。\n")
    f.write("        /// 先按完整键查，再退回**只看行号** —— 后者才是与游戏语音文件一致的口径。\n")
    f.write("        /// </summary>\n")
    f.write("        public static bool IsVoiced(string key)\n")
    f.write("        {\n")
    f.write("            if (string.IsNullOrEmpty(key)) return false;\n")
    f.write("            if (Voiced.Contains(key)) return true;\n")
    f.write("            int slash = key.IndexOf('/');\n")
    f.write("            string id = slash >= 0 ? key.Substring(slash + 1) : key;\n")
    f.write("            if (id.Length > 0 && id[0] == '~') id = id.Substring(1);\n")
    f.write("            return id.Length > 0 && VoicedIds.Contains(id);\n")
    f.write("        }\n")
    f.write("    }\n}\n")

with open(os.path.join(OUTDIR, "SpeakerNames.cs"), "w", encoding=enc, newline=nl) as f:
    f.write("// <auto-generated> by gen_voicelist.py — do not edit by hand.\n")
    f.write("// AuthorId -> 中文显示名，取自游戏 zh-CN 源 CharacterNames 文档。\n")
    f.write("using System.Collections.Generic;\n\nnamespace NoExistenceA11y\n{\n")
    f.write("    internal static class SpeakerNames\n    {\n")
    f.write("        public static readonly Dictionary<string, string> Map = new Dictionary<string, string>\n        {\n")
    for k in sorted(names):
        f.write('            { "%s", "%s" },\n' % (k, names[k]))
    f.write("        };\n\n")
    f.write("        /// <summary>查不到就退回原始 AuthorId（宁可念个英文 ID，也不要静默丢人）。</summary>\n")
    f.write("        public static string Resolve(string authorId)\n        {\n")
    f.write("            if (string.IsNullOrEmpty(authorId)) return null;\n")
    f.write("            string v;\n")
    f.write("            return Map.TryGetValue(authorId, out v) && !string.IsNullOrEmpty(v) ? v : authorId;\n")
    f.write("        }\n    }\n}\n")

for n in ("VoiceLineIds.cs", "SpeakerNames.cs"):
    p = os.path.join(OUTDIR, n)
    print("written %-18s %6d bytes" % (n, os.path.getsize(p)))
